[build]
command = """
composer install --no-dev -n \
&& ./vendor/bin/drush tome:install -y \
&& ./vendor/bin/drush cim -y \
&& ./vendor/bin/drush cron \
&& ./vendor/bin/drush locale:update \
&& ./vendor/bin/drush simple-sitemap:generate -l $URL \
&& ./vendor/bin/drush un lb_claro \
&& ./vendor/bin/drush tome:static -l $URL
# && rm -rf html \
# && ./vendor/bin/drush tome:static -l $URL \
# && cp html/404/index.html html/404.html \
# && cp web/themes/custom/vr/favicons/android-chrome-192x192.png html/themes/custom/vr/favicons/android-chrome-192x192.png \
# && cp web/themes/custom/vr/favicons/android-chrome-512x512.png html/themes/custom/vr/favicons/android-chrome-512x512.png
"""

# Example lines you can add before "tome:static" above if needed:
#&& LUNR_DRUSH=./vendor/bin/drush node web/modules/contrib/lunr/js/index.node.js default \
#&& ./vendor/bin/drush simple-sitemap-generate -y -l $DEPLOY_PRIME_URL \

publish = "html"

[build.environment]
PHP_VERSION="8.1"

[[redirects]]
from = "/home"
to = "/"
status = 301
