[build]
command = """
export PATH="./vendor/bin:$PATH"

drush tome:install -y \
&& drush cr \
&& drush cron \
&& drush simple-sitemap:generate -l $URL \
&& drush pmu project_browser \
&& drush tome:static -l $URL
"""

# && drush locale:update \
# && mkdir -p html/themes/custom/vr/img \
# && cp -r web/themes/custom/vr/img/homepage.jpg html/themes/custom/vr/img \
# && drush cim -y \
# && rm -rf html \
# && drush tome:static -l $URL \
# && cp html/404/index.html html/404.html \
# && cp web/themes/custom/vr/favicons/android-chrome-192x192.png html/themes/custom/vr/favicons/android-chrome-192x192.png \
# && cp web/themes/custom/vr/favicons/android-chrome-512x512.png html/themes/custom/vr/favicons/android-chrome-512x512.png

# Example lines you can add before "tome:static" above if needed:
#&& LUNR_DRUSH=drush node web/modules/contrib/lunr/js/index.node.js default \
#&& drush simple-sitemap-generate -y -l $DEPLOY_PRIME_URL \

publish = "html"

[build.environment]
PHP_VERSION="8.3"

[[redirects]]
from = "/home"
to = "/"
status = 301

# https://www.netlify.com/blog/how-to-schedule-deploys-with-netlify/
[functions]
  node_bundler = "esbuild"
