settings:
  plugins:
    ckeditor5_codeBlock:
      languages:
        0:
          label: 'Testo semplice'
        4:
          label: CSS
        6:
          label: HTML
        8:
          label: JavaScript
        9:
          label: PHP
