_core:
  default_config_hash: LQ8APF498SWWO_LQuJV1zq8TYAB6VRhNiCRKY9d9YmY
langcode: it
maxlength_block_class_field: 255
field_type: multiple_textfields
default_case: standard
block_classes_stored:
  - d-inline-flex
  - justify-content-center
enable_attributes: false
enable_auto_complete: true
qty_classes_per_block: 10
items_per_page: 50
enable_special_chars: false
qty_attributes_per_block: 10
enable_id_replacement: false
weight_attributes: null
weight_class: null
weight_id: null
filter_html_clean_css_identifier: ''
maxlength_attributes: 10000
maxlength_id: 255
