_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  background_image_formatter: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  coffee: 0
  config: 0
  contact: 0
  contact_block: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  geofield: 0
  gin_toolbar: 0
  gtranslate: 0
  help: 0
  history: 0
  image: 0
  image_effects: 0
  image_style_quality: 0
  inline_entity_form: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_discovery: 0
  lb_claro: 0
  leaflet: 0
  leaflet_more_maps: 0
  leaflet_views: 0
  link: 0
  linkit: 0
  locale: 0
  mapper: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_routes: 0
  metatag_twitter_cards: 0
  minifyhtml: 0
  node: 0
  nomarkup: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  project_browser: 0
  redirect: 0
  rest: 0
  scraper: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_ui: 0
  sqlite: 0
  storage: 0
  svg_image: 0
  system: 0
  tagify: 0
  taxonomy: 0
  text: 0
  textimage: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_netlify_contact: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  twig_field_value: 0
  ui_patterns: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_views: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_geojson: 0
  views_ui: 0
  pathauto: 1
  views: 10
  standard: 1000
theme:
  claro: 0
  stable9: 0
  bootstrap5: 0
  vr: 0
  gin: 0
profile: standard
