_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  coffee: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  lb_claro: 0
  link: 0
  linkit: 0
  locale: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_favicons: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_routes: 0
  metatag_twitter_cards: 0
  minifyhtml: 0
  node: 0
  nomarkup: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  redirect: 0
  scraper: 0
  sdc: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  sqlite: 0
  svg_image: 0
  system: 0
  tagify: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_netlify_contact: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  twbstools: 0
  twig_field_value: 0
  ui_patterns: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_views: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  seeds_toolbar: 100
  standard: 1000
theme:
  claro: 0
  stable9: 0
  bootstrap5: 0
  vr: 0
profile: standard
