_core:
  default_config_hash: eaXmaPSud65p-XhTwMIL9vKETD9zR3qNOMMa5EUuoNw
color_selector:
  plugin_id: html_color
  plugin_settings:
    html_color: {  }
image_selector:
  plugin_id: dropdown
  plugin_settings:
    basic: {  }
    dropdown:
      path: themes/custom/vr
font_selector:
  plugin_id: dropdown
  plugin_settings:
    basic: {  }
    dropdown:
      path: themes/custom/vr/fonts
