_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
langcode: it
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    it: it
  domains:
    it: ''
selected_langcode: site_default
