thunderforest_api_key: 9210b0db958747ff8568be59d9fbe236
mapbox_access_token: ''
here_api_key: ''
navionics_api_key: ''
navionics_authorized_domain: ''
leaflet_more_maps_custom_maps:
  1:
    map-key: Paragliding
    layer-keys:
      'bing hybrid layer': 'bing hybrid layer'
      'google-hybrid layer': 'google-hybrid layer'
      'google-high-res terrain': 'google-high-res terrain'
      'osm-landscape layer': 'osm-landscape layer'
      'osm-outdoors layer': 'osm-outdoors layer'
      'opentopomap layer': 'opentopomap layer'
      'tracestrack-topo-base layer': 'tracestrack-topo-base layer'
      'bing satellite layer': 0
      'bing road layer': 0
      'esri-world_imagery layer': 0
      'esri-natgeo_world_map layer': 0
      'esri-world_physical_map layer': 0
      'esri-ocean_world_ocean_base layer': 0
      'esri-world_topo_map layer': 0
      'esri-world_street_map layer': 0
      'google-hybrid overlay': 0
      'google-satellite layer': 0
      'google-roadmap layer': 0
      'google-high-res roadmap': 0
      'mapbox-dark layer': 0
      'mapbox-light layer': 0
      'mapbox-satellite-streets layer': 0
      'mapbox-streets layer': 0
      'mapycz-basic layer': 0
      'mapycz-outdoor layer': 0
      'mapycz-winter layer': 0
      'mapycz-aerial layer': 0
      'osm-de layer': 0
      'osm-cycle layer': 0
      'osm-transport layer': 0
      'osm-transport-dark layer': 0
      'osm-spinal-map layer': 0
      'osm-pioneer layer': 0
      'osm-mobile-atlas layer': 0
      'osm-neighbourhood layer': 0
      'stamen-terrain layer': 0
      'stamen-terrain-background layer': 0
      'stamen-terrain-labels layer': 0
      'stamen-terrain-lines layer': 0
      'stamen-toner layer': 0
      'stamen-toner-background layer': 0
      'stamen-toner-hybrid layer': 0
      'stamen-toner-labels layer': 0
      'stamen-toner-lines layer': 0
      'stamen-toner-lite layer': 0
      'stamen-watercolor layer': 0
      'here-base layer': 0
      'navionics nautical-non-transparent': 0
      'navionics sonar': 0
      'navionics ski': 0
      'tracestrack-carto-base layer': 0
    reverse-order: 1
mapycz_api_key: ''
tracestrack_api_key: b9c2fabd9b0774eb89ea495c32bb7c91
