_core:
  default_config_hash: tDsFI2oUIQzmq98W7R-xWBt9A62zFCrDxL88Hzx0_aE
executables:
  composer: null
  rsync: null
additional_trusted_composer_plugins: {  }
include_unknown_files_in_project_root: false
