_core:
  default_config_hash: TgohPSKQv6vKfToguTCvb8Wp899q7b2l_Rh4sVKDmBs
enabled_sources:
  - drupalorg_jsonapi
  - recipes
  - drupal_core
allow_ui_install: true
allowed_projects: {  }
max_selections: null
