_core:
  default_config_hash: FsPoQBR9MKSFgJCNizl60cAUjLthj3EPn9ii_6rmFws
compact: 1
search: 1
style: light
support: 'https://ventorelativo.netlify.app/'
custom_style: ''
light_logo: ''
dark_logo: ''
fixed_elements: 0
langcode: it
