_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: it
uuid: 69e67bfd-86b4-4d26-842d-a2949abde282
name: 'Service Termoidraulica'
mail: alessandro.gandi@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: it
mail_notification: ''
