_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: it
uuid: 69e67bfd-86b4-4d26-842d-a2949abde282
name: Ventorelativo
mail: segreteria@ventorelativo.it
slogan: 'Parapendio Club'
page:
  403: ''
  404: /node/3
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: it
mail_notification: ''
