_core:
  default_config_hash: t7clj3mzmOGrXX0HuCH5usf0vEqRtnMTBFVBIEmZ5pc
first_day: 1
country:
  default: IT
timezone:
  default: Europe/Rome
  user:
    configurable: false
    default: 0
    warn: false
