_core:
  default_config_hash: Uhi8_qZk4TddoUw18rRiUrCaca1r3640z2KyXy8VJMQ
langcode: it
debug: false
default_extension: png
url_generation:
  enabled: true
  text_separator: '---'
default_font:
  name: 'Metropolis Bold'
  uri: themes/custom/vr/fonts/Metropolis-Bold.ttf
